/* 定义项目名称,也是所有生成的源码文件名前缀 */

/*
 * Generated by erpcgen 1.12.0 on Tue Jan 30 06:17:59 2024.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#include "c_erpcdemo_client.h"
#include "erpcdemo_client.hpp"
#include "erpc_manually_constructed.hpp"

using namespace erpc;
using namespace std;
using namespace erpcShim;


#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
DEMO_client *s_DEMO_client = nullptr;
#else
ERPC_MANUALLY_CONSTRUCTED_STATIC(DEMO_client, s_DEMO_client);
#endif

binary_t * RD_demoHello(const binary_t * txInput)
{
    binary_t * result = NULL;
    result = s_DEMO_client->RD_demoHello(txInput);

    return result;
}

void initDEMO_client(erpc_client_t client)
{
#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
    erpc_assert(s_DEMO_client == nullptr);
    s_DEMO_client = new DEMO_client(reinterpret_cast<ClientManager *>(client));
#else
    erpc_assert(!s_DEMO_client.isUsed());
    s_DEMO_client.construct(reinterpret_cast<ClientManager *>(client));
#endif
}

void deinitDEMO_client(void)
{
#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
    if (s_DEMO_client != nullptr)
    {
        delete s_DEMO_client;
        s_DEMO_client = nullptr;
    }
#else
    s_DEMO_client.destroy();
#endif
}
