/* 定义项目名称,也是所有生成的源码文件名前缀 */

/*
 * Generated by erpcgen 1.12.0 on Tue Jan 30 06:17:59 2024.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_c_erpcdemo_server_h_)
#define _c_erpcdemo_server_h_

#include "erpcdemo_common.h"

#if defined(__cplusplus)
extern "C"
{
#endif

typedef void * erpc_service_t;

#if !defined(ERPC_FUNCTIONS_DEFINITIONS)
#define ERPC_FUNCTIONS_DEFINITIONS


/*! @brief DEMO identifiers */
enum _DEMO_ids
{
    kDEMO_service_id = 1,
    kDEMO_RD_demoHello_id = 1,
};

/*! 定义服务接口函数 */
//! @name DEMO
//@{
binary_t * RD_demoHello(const binary_t * txInput);
//@}


#endif // ERPC_FUNCTIONS_DEFINITIONS

/*! @brief Return DEMO_service service object. */
erpc_service_t create_DEMO_service(void);

/*! @brief Destroy DEMO_service service object. */
void destroy_DEMO_service(erpc_service_t service);


#if defined(__cplusplus)
}
#endif

#endif // _c_erpcdemo_server_h_
