/* 定义项目名称,也是所有生成的源码文件名前缀 */

/*
 * Generated by erpcgen 1.12.0 on Tue Jan 30 06:17:59 2024.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_erpcdemo_client_hpp_)
#define _erpcdemo_client_hpp_

#include "erpcdemo_interface.hpp"

#include "erpc_client_manager.h"

namespace erpcShim
{

class DEMO_client: public DEMO_interface
{
    public:
        DEMO_client(erpc::ClientManager *manager);

        virtual ~DEMO_client();

        virtual binary_t * RD_demoHello(const binary_t * txInput);

    protected:
        erpc::ClientManager *m_clientManager;
};

} // erpcShim


#endif // _erpcdemo_client_hpp_
