/* 定义项目名称,也是所有生成的源码文件名前缀 */

/*
 * Generated by erpcgen 1.12.0 on Tue Jan 30 06:17:59 2024.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_erpcdemo_server_hpp_)
#define _erpcdemo_server_hpp_

#include "erpcdemo_interface.hpp"

#include "erpc_server.hpp"
#include "erpc_codec.hpp"

#if 11200 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


namespace erpcShim
{

/*!
 * @brief Service subclass for DEMO.
 */
class DEMO_service : public erpc::Service
{
public:
    DEMO_service(DEMO_interface *_DEMO_interface);

    virtual ~DEMO_service();

    /*! @brief return service interface handler. */
    DEMO_interface* getHandler(void);

    /*! @brief Call the correct server shim based on method unique ID. */
    virtual erpc_status_t handleInvocation(uint32_t methodId, uint32_t sequence, erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, erpc::Transport * transport);

private:
    DEMO_interface *m_handler;
    /*! @brief Server shim for RD_demoHello of DEMO interface. */
    erpc_status_t RD_demoHello_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, erpc::Transport * transport, uint32_t sequence);
};

} // erpcShim


#endif // _erpcdemo_server_hpp_
