/* 定义项目名称,也是所有生成的源码文件名前缀 */

/*
 * Generated by erpcgen 1.12.0 on Tue Jan 30 06:17:59 2024.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_erpcdemo_interface_hpp_)
#define _erpcdemo_interface_hpp_

#include "erpcdemo_common.hpp"

namespace erpcShim
{


// Abstract base class for DEMO
class DEMO_interface
{
    public:
        static const uint8_t m_serviceId = 1;
        static const uint8_t m_RD_demoHelloId = 1;

        virtual ~DEMO_interface(void);

        virtual binary_t * RD_demoHello(const binary_t * txInput) = 0;
private:
};
} // erpcShim


#endif // _erpcdemo_interface_hpp_
